language: node_js
version: 1.0
node_js:
  - node
branches:
  only:
    - main
    - "/^v?\\d{1}\\.\\d{1,2}.\\d{1,2}$/"

# script:
#   - echo $NPM_AUTH_TOKEN
#   - npm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
notifications:
  email:
    recipients:
      - luxuemin2108@gmail.com
    on_success: never
    on_failure: always

jobs:
  include:
    # - stage: test
    #   name: 'Unit Tests'
    #   script: 'npm run test'
    - stage: deploy
      script: 'npm run build'
      name: 'Deploy to NPM'
      deploy:
        provider: npm
        email: luxuemin2108@gmail.com
        api_key: $NPM_AUTH_TOKEN
        on:
          repo: jackluson/babel-plugin-styled-components-px2vw
          branch: main
        skip_cleanup: 'true'
# before_deploy: npm run build
# deploy:
#   provider: npm
#   email: luxuemin2108@gmail.com
#   api_key: $NPM_AUTH_TOKEN
#   on:
#     repo: jackluson/babel-plugin-styled-components-px2vw
#     branch: main
#   skip_cleanup: 'true'
